neilson_calldown/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'
  get "tickets" => "pages#tickets"
  devise_for :models

end

neilson_calldown/app/models/itemmaster.rb
class Itemmaster < ActiveRecord::Base
end

neilson_calldown/app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

neilson_calldown/app/models/qoh.rb
class Qoh < ActiveRecord::Base
end

neilson_calldown/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

neilson_calldown/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

neilson_calldown/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

neilson_calldown/app/helpers/application_helper.rb
module ApplicationHelper
end

neilson_calldown/app/helpers/pages_helper.rb
module PagesHelper
end

neilson_calldown/app/views/layouts/_header.html.erb
<nav class="navbar navbar-static top navbar-default" role="navigation">
<div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",root_path%><li>
    <% if user_signed_in? %>
        <li><%= link_to "Tickets",tickets_path%><li>
        <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

neilson_calldown/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NeilsonCalldown</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<%=render 'layouts/header' %>
<div class="container">
	<% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-info") %>
<% end %>
<%= yield %>
</div>
</body>
</html>

neilson_calldown/app/views/pages/home.html.erb
<div class="jumbotron center">
     <h1>Call-down App</h1>
     <% if user_signed_in? %>
          # do something
     <% else %>
       <p>
         <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
         <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
       </p>
  <% end %>  
</div>